{
  "formatVersion": "1.1",
  "component": {
    "group": "com.optimusyazilim.oha_sdk_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.jonhanson.flutter_native_splash",
          "module": "flutter_native_splash_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.wakelock",
          "module": "wakelock_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.libphonenumber_plugin",
          "module": "libphonenumber_plugin_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 12576942,
          "sha512": "e0c213f9852fa979e4f9087b3317491c9a379a3beb395d0d38865e3a71da4fdae99772e54b08c1a5dc609511b68477b3fad63573ad9d0bda1fcadda1b550c25e",
          "sha256": "9b29a688f391dde8186194eda68443088ab792c15a323a35010f7ff441eb1343",
          "sha1": "a40520ad8c9bfa0849a8cf94bec1bdcdeaa9756d",
          "md5": "a37d71cce82f3be7a90be0e6a65ad80e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.jonhanson.flutter_native_splash",
          "module": "flutter_native_splash_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.wakelock",
          "module": "wakelock_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.libphonenumber_plugin",
          "module": "libphonenumber_plugin_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 12576942,
          "sha512": "e0c213f9852fa979e4f9087b3317491c9a379a3beb395d0d38865e3a71da4fdae99772e54b08c1a5dc609511b68477b3fad63573ad9d0bda1fcadda1b550c25e",
          "sha256": "9b29a688f391dde8186194eda68443088ab792c15a323a35010f7ff441eb1343",
          "sha1": "a40520ad8c9bfa0849a8cf94bec1bdcdeaa9756d",
          "md5": "a37d71cce82f3be7a90be0e6a65ad80e"
        }
      ]
    }
  ]
}
