{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.2.aar",
          "url": "image_picker_android_release-1.2.aar",
          "size": 66668,
          "sha512": "59e1aa8bfebd6b88b8eeecf81920b2b854f9d1599ae8c18e8010aa55dc2adf74720b85f69242d9e6ab2d929ae9f263062cdc75780a48c635505ab6d8615b0a84",
          "sha256": "27047525999a7c19ac342899de242715e0ed0403f67ec3d9bf2e7f96d4f767fa",
          "sha1": "7cfa6422bc0777d9decb3c5d485a32258c6bb461",
          "md5": "ecbf396ac8a3a71bcedabbc210b13113"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.2.aar",
          "url": "image_picker_android_release-1.2.aar",
          "size": 66668,
          "sha512": "59e1aa8bfebd6b88b8eeecf81920b2b854f9d1599ae8c18e8010aa55dc2adf74720b85f69242d9e6ab2d929ae9f263062cdc75780a48c635505ab6d8615b0a84",
          "sha256": "27047525999a7c19ac342899de242715e0ed0403f67ec3d9bf2e7f96d4f767fa",
          "sha1": "7cfa6422bc0777d9decb3c5d485a32258c6bb461",
          "md5": "ecbf396ac8a3a71bcedabbc210b13113"
        }
      ]
    }
  ]
}
