{
  "formatVersion": "1.1",
  "component": {
    "group": "com.optimusyazilim.oha_sdk_module",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.jonhanson.flutter_native_splash",
          "module": "flutter_native_splash_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.wakelock",
          "module": "wakelock_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.libphonenumber_plugin",
          "module": "libphonenumber_plugin_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23664501,
          "sha512": "0616b144799598b97b8b1794513b4452c91e28dc010e3e55374efa6faec419d86355c4100e3c53ec40e5301e594eba2946eef58be15519d5c04f4d2667199590",
          "sha256": "87160ff3e58a4d4ee4291a7272dd1d4284953fd5676ab8d71c672fc04adbaa26",
          "sha1": "d331e7c720fcad90c588ec1726308a2bf23cd961",
          "md5": "3984efb892b2f7926ac91b1052cd8a9b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-cf7a9d0800f2a5da166dbe0eb9fb2476018269b1"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "net.jonhanson.flutter_native_splash",
          "module": "flutter_native_splash_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.wakelock",
          "module": "wakelock_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.libphonenumber_plugin",
          "module": "libphonenumber_plugin_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.FlutterToast",
          "module": "fluttertoast_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 23664501,
          "sha512": "0616b144799598b97b8b1794513b4452c91e28dc010e3e55374efa6faec419d86355c4100e3c53ec40e5301e594eba2946eef58be15519d5c04f4d2667199590",
          "sha256": "87160ff3e58a4d4ee4291a7272dd1d4284953fd5676ab8d71c672fc04adbaa26",
          "sha1": "d331e7c720fcad90c588ec1726308a2bf23cd961",
          "md5": "3984efb892b2f7926ac91b1052cd8a9b"
        }
      ]
    }
  ]
}
